# Generated by Django 6.0.3 on 2026-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='invite',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
