# Generated by Django 6.0.3 on 2026-05-06 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0002_server_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='invite',
            field=models.CharField(blank=True, default=uuid.uuid7, null=True, unique=True),
        ),
    ]
