# Generated by Django 6.0.3 on 2026-05-06 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0003_alter_server_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='invite',
            field=models.CharField(blank=True, default=uuid.uuid7, null=True),
        ),
    ]
