# Generated by Django 6.0.5 on 2026-05-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0005_server_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_channels', to='callapp.server'),
        ),
        migrations.CreateModel(
            name='VoiceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_channels', to='callapp.server')),
            ],
        ),
    ]
