# Generated by Django 6.0.5 on 2026-05-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0006_alter_channel_server_voicechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='callapp.server'),
        ),
    ]
