# Generated by Django 6.0.5 on 2026-05-29 20:17

import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0007_alter_channel_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='invite',
            field=models.CharField(blank=True, default=uuid_utils._uuid_utils.uuid7, null=True),
        ),
    ]
